
spring.application.name=polyhub
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/polyhub?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb+srv://POLYHUB_DB:POLYHUB@polyhub.reph6nz.mongodb.net/polyhub_chat?retryWrites=true&w=majority&appName=POLYHUB
<<<<<<< HEAD
<<<<<<< HEAD
=======
spring.mongodb.uri=mongodb+srv://POLYHUB_DB:POLYHUB@polyhub.reph6nz.mongodb.net/polyhub_chat?retryWrites=true&w=majority&appName=POLYHUB

>>>>>>> b97c3c267eb6d6ba53fb865b3901f4c020c4057e
=======
spring.mongodb.uri=mongodb+srv://POLYHUB_DB:POLYHUB@polyhub.reph6nz.mongodb.net/polyhub_chat?retryWrites=true&w=majority&appName=POLYHUB

>>>>>>> b97c3c267eb6d6ba53fb865b3901f4c020c4057e

server.port=8080

# Cấu hình giới hạn kích thước file tải lên (Fix lỗi MaxUploadSizeExceededException)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Cloudinary Configuration
cloudinary.cloud_name=dueb9a4d9
cloudinary.api_key=355974684552594
cloudinary.api_secret=RMcyJX2hM5TH7YFCUgL2-WR6I40

# Gemini AI Configuration
<<<<<<< HEAD
<<<<<<< HEAD
gemini.api.key=AIzaSyDQ8VF_dVp8dJ_SanHrr9PJ6CfWk_W_x5U
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent

# Spring Mail Configuration
=======
=======
>>>>>>> b97c3c267eb6d6ba53fb865b3901f4c020c4057e
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=

# Email Sender Configuration
<<<<<<< HEAD
>>>>>>> b97c3c267eb6d6ba53fb865b3901f4c020c4057e
=======
>>>>>>> b97c3c267eb6d6ba53fb865b3901f4c020c4057e
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nmn00525@gmail.com
spring.mail.password=xksl cywc bxha kvcn
spring.mail.properties.mail.smtp.auth=true
<<<<<<< HEAD
<<<<<<< HEAD
spring.mail.properties.mail.smtp.starttls.enable=true

# Encoding Configuration
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8

# Disable Caching for Development
spring.thymeleaf.cache=false
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
=======
spring.mail.properties.mail.smtp.starttls.enable=true
>>>>>>> b97c3c267eb6d6ba53fb865b3901f4c020c4057e
=======
spring.mail.properties.mail.smtp.starttls.enable=true
>>>>>>> b97c3c267eb6d6ba53fb865b3901f4c020c4057e
