spring.application.name=polyhub
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=polyhub;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.data.mongodb.uri=mongodb://localhost:27017/polyhub_nosql

server.port=8080

# Cấu hình giới hạn kích thước file tải lên (Fix lỗi MaxUploadSizeExceededException)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Cloudinary Configuration
cloudinary.cloud_name=dueb9a4d9
cloudinary.api_key=355974684552594
cloudinary.api_secret=RMcyJX2hM5TH7YFCUgL2-WR6I40
