name: Deploy Backend to Hugging Face Spaces

on:
  push:
    branches: [dev]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Subdirectory to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
        run: |
          # Cấu hình thông tin Git bot
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Di chuyển vào thư mục backend và khởi tạo git tạm thời
          cd backend
          git init -b main
          git add .
          git commit -m "Deploy latest backend from GitHub monorepo"
          
          # Push đè lên Hugging Face Space của bạn
          git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/polyhub-backend main
